### PR TITLE
Scroll List, Darkmode, small fixes

### PR DESCRIPTION
**Pull request by ebert-l**
User Liste ist jetzt alleine scrollbar, ohne die Navigation weg zu scrollen.

### CODE REVIEW

**Comment by ebert-l** [comment]
Darkmode kann gestartet werden, wenn man auf den Bierkrug oben links klickt

**Comment by maseiler** [comment]
Very nice work! I'd love to have a few quick fixes before I merge it into production:
- General:
	- change user selection color t(yellow is an indicator, that a user's account is almost full)
	- a dedicated switch button in `NavBar` 
		- e.g. [this icon](https://fontawesome.com/icons/moon-over-sun?s=solid&f=classic) or something else
	- Feedback button: white font
- Home page:
	- only half of the page has enabled dark mode
- Statistic page:
	- sidebar: white font
	- background
- admin page:
	- sidebar: white font
	- User/Item/Booking list: white font for field `ID`
	- Feedback: `ID` , `Timestamp` white font
	- Feedback: text fields still white
	
Feature request
- adjust automatically based on current time

**Comment by ebert-l** [comment]
All Fixes are now implemented.
The feature Request with the time-based color switching will be provided as a seperate merge.

**Comment by ebert-l** [comment]
Time based switching is now implemented. Check-Interval is set to 10s.
The manual switch is obsolete with automatic switching enabled. Therefore the switch is no longer visible while using time based theme switching.
If you want to disable automatic mode and go back to manual switching, you just need to change the value of 'automaticThemeSwitching' to false in NavBar.vue

**Review by ebert-l — COMMENTED** [review]
10/10 would recommend

**Comment by ebert-l** [comment]
Too many changes in one PR.
I will separate the changes in three different PRs.

**Pull request closed without merging**
